services:
  - type: web
    name: portfolio
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_EMAILJS_SERVICE_ID
        sync: false
      - key: VITE_EMAILJS_TEMPLATE_ID
        sync: false
      - key: VITE_EMAILJS_PUBLIC_KEY
        sync: false
